### PR TITLE
Bump `Buefy` to `v0.9.28`

### PR DESCRIPTION
**Pull request by wesdevpro**
### Proposed Changes
- Update `Buefy` for `nuxt-buefy` to the latest version of `v0.9.28`
- Bump the minor version of `nuxt-buefy` to `v0.4.28`

As requested here: https://github.com/buefy/buefy/pull/4011

### CODE REVIEW

**Review by kikuomax — APPROVED** [review]
Looks good to me!

**Comment by wesdevpro** [comment]
Note: the force push was to amend the commit `bump: nuxt to v2.17.2` to `bump: nuxt to v2.17.3`

**Review by miroslavgeorgiev — APPROVED** [review]

**Comment by miroslavgeorgiev** [comment]
The version is not updated yet in the NPM - can you publish it there?
https://www.npmjs.com/package/nuxt-buefy?activeTab=versions

**Comment by kikuomax** [comment]
> The version is not updated yet in the NPM - can you publish it there? https://www.npmjs.com/package/nuxt-buefy?activeTab=versions

@miroslavgeorgiev @wesdevpro GitHub Actions workflow for publishing npm package failed with:
```
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! Invalid: lock file's buffer@4.9.2 does not satisfy buffer@6.0.3
npm ERR! Missing: buffer@4.9.2 from lock file
```

There is something wrong with `package-lock.json`. Removing `node_modules`, `package-lock.json` and `yarn.lock`, and re-running `npm install` did not solve the problem on my machine (M1 MacBook, Node.js v18).

I found dependencies related to `nuxt@2.17.3` required different `buffer` versions:
- `@nuxt/cli` → `crc` → `buffer>=6.0.3` (in `peerDependencies`)
- `@nuxt/webpack` → `webpackbar` → `webpack` → `node-libs-browser` → `buffer^4.3.0` (in `dependencies`)

Since the requirement for `buffer>=6.0.3` is in `peerDependencies`, it is user's responsibility to install `buffer>=6.0.3`. As we did not explicitly install `buffer>=6.0.3`, we ended up with `buffer@4.9.2` installed.

**Comment by miroslavgeorgiev** [comment]
> > The version is not updated yet in the NPM - can you publish it there? https://www.npmjs.com/package/nuxt-buefy?activeTab=versions
> 
> @miroslavgeorgiev @wesdevpro GitHub Actions workflow for publishing npm package failed with:
> 
> ```
> npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
> npm ERR! 
> npm ERR! Invalid: lock file's buffer@4.9.2 does not satisfy buffer@6.0.3
> npm ERR! Missing: buffer@4.9.2 from lock file
> ```
> 
> There is something wrong with `package-lock.json`. Removing `node_modules`, `package-lock.json` and `yarn.lock`, and re-running `npm install` did not solve the problem on my machine (M1 MacBook, Node.js v18).
> 
> I found dependencies related to `nuxt@2.17.3` required different `buffer` versions:
> 
> * `@nuxt/cli` → `crc` → `buffer>=6.0.3` (in `peerDependencies`)
> * `@nuxt/webpack` → `webpackbar` → `webpack` → `node-libs-browser` → `buffer^4.3.0` (in `dependencies`)
> 
> Since the requirement for `buffer>=6.0.3` is in `peerDependencies`, it is user's responsibility to install `buffer>=6.0.3`. As we did not explicitly install `buffer>=6.0.3`, we ended up with `buffer@4.9.2` installed.

This is really strange.
I checked our company apps - on all of them we're on `Nuxt 2.17.3` and inside the `package-lock` file we've ended up with:
```
"node_modules/buffer": {
      "version": "4.9.2",
      "resolved": "https://registry.npmjs.org/buffer/-/buffer-4.9.2.tgz",
      "integrity": "sha512-xq+q3SRMOxGivLhBNaUdC64hDTQwejJ+H0T/NB1XMtTVEwNTrfFF3gAxiyW0Bu/xWEGhjVKgUcMhCrUy2+uCWg==",
      "dependencies": {
        "base64-js": "^1.0.2",
        "ieee754": "^1.1.4",
        "isarray": "^1.0.0"
      }
    },
 ```
 As we've followed the same strategy as you:
 - delete `node_modules` folder and `package-lock` file
 - run `npm install` and no problems so far, but we lack using `yarn`
 - NodeJS version we use is ^20 but I doubt the problem is there
 
 So I checked the master branch here:
 - with npm ci - I got the same error
 - if I delete package-lock, yarn.lock and node_modules, then execute first `npm install` then `npm ci` (for the github action) - it passes correct, but no yarn.lock is created (I dont use it)
 
 I can create a PR for you to check

**Comment by kikuomax** [comment]
@miroslavgeorgiev Thank you for investigating the error. I tried Node v20.x:
1. I switched my Node.js to v20.11.1 (npm v10.2.4).
2. I deleted `package-loc.json`, `yarn.lock`, and `node_modules`.
3. I ran `npm install`.
4. I ran `npm ci`.
5. I got the same error.

We worked around the issue by explicitly installing `buffer@6.0.3` (#152), and `nuxt-buefy` v0.4.28 was successfully published. If the latest `nuxt-buefy` had any problem, we would appreciate your PR.

**Comment by miroslavgeorgiev** [comment]
It is working now, so thank you too :)

**Pull request merged**
